<a href="https://colab.research.google.com/github/Leulassaminew/titanic-survivors-prediction/blob/main/titanic_first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [122]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
test = pd.read_csv('/content/test (1).csv')
train = pd.read_csv('/content/train (1).csv')

In [108]:
test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [109]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [123]:
x = train.drop(["Survived","Name","Ticket","Cabin","Parch"],axis = 1)
y = train["Survived"]

In [124]:
xtest = test.drop(["Name","Ticket","Cabin","Parch"],axis = 1)
xtest["Age"]=xtest["Age"].fillna(30)
xtest["Embarked"]=xtest["Embarked"].fillna("S")
xtest["Fare"]=xtest["Fare"].fillna(8.0)

In [104]:
xtest

PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0            892       3    male  34.5      0      0    7.8292        Q
1            893       3  female  47.0      1      0    7.0000        S
2            894       2    male  62.0      0      0    9.6875        Q
3            895       3    male  27.0      0      0    8.6625        S
4            896       3  female  22.0      1      1   12.2875        S
..           ...     ...     ...   ...    ...    ...       ...      ...
413         1305       3    male  30.0      0      0    8.0500        S
414         1306       1  female  39.0      0      0  108.9000        C
415         1307       3    male  38.5      0      0    7.2500        S
416         1308       3    male  30.0      0      0    8.0500        S
417         1309       3    male  30.0      1      1   22.3583        C

[418 rows x 8 columns]

In [97]:
xtest

PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0            892       3    male  34.5      0      0    7.8292        Q
1            893       3  female  47.0      1      0    7.0000        S
2            894       2    male  62.0      0      0    9.6875        Q
3            895       3    male  27.0      0      0    8.6625        S
4            896       3  female  22.0      1      1   12.2875        S
..           ...     ...     ...   ...    ...    ...       ...      ...
413         1305       3    male  30.0      0      0    8.0500        S
414         1306       1  female  39.0      0      0  108.9000        C
415         1307       3    male  38.5      0      0    7.2500        S
416         1308       3    male  30.0      0      0    8.0500        S
417         1309       3    male  30.0      1      1   22.3583        C

[418 rows x 8 columns]

In [110]:
x

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0              1       3    male  22.0      1      0   7.2500        S
1              2       1  female  38.0      1      0  71.2833        C
2              3       3  female  26.0      0      0   7.9250        S
3              4       1  female  35.0      1      0  53.1000        S
4              5       3    male  35.0      0      0   8.0500        S
..           ...     ...     ...   ...    ...    ...      ...      ...
886          887       2    male  27.0      0      0  13.0000        S
887          888       1  female  19.0      0      0  30.0000        S
888          889       3  female  30.0      1      2  23.4500        S
889          890       1    male  26.0      0      0  30.0000        C
890          891       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [125]:
x["Age"]=x["Age"].fillna(30)
x["Embarked"]=x["Embarked"].fillna("S")

<bound method NDFrame.describe of      PassengerId  Pclass     Sex  \
0              1       3    male   
1              2       1  female   
2              3       3  female   
3              4       1  female   
4              5       3    male   
..           ...     ...     ...   
886          887       2    male   
887          888       1  female   
888          889       3  female   
889          890       1    male   
890          891       3    male   

                                                   Age  SibSp  Parch     Fare  \
0                                                 22.0      1      0   7.2500   
1                                                 38.0      1      0  71.2833   
2                                                 26.0      0      0   7.9250   
3                                                 35.0      1      0  53.1000   
4                                                 35.0      0      0   8.0500   
..                                             

In [82]:
x['Age'].isna().sum()

0

In [120]:
x["Parch"].value_counts()

0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: Parch, dtype: int64

In [121]:
xtest["Parch"].value_counts()

0    324
1     52
2     33
3      3
4      2
9      2
6      1
5      1
Name: Parch, dtype: int64

In [126]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
catagorical_features = ["Pclass","Sex","SibSp","Embarked"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                one_hot,
                                 catagorical_features)],
                                remainder = "passthrough")
t_x = transformer.fit_transform(x)
tt = transformer.fit_transform(xtest)

In [100]:
t_x

array([[  0.    ,   0.    ,   1.    , ...,   1.    ,  22.    ,   7.25  ],
       [  1.    ,   0.    ,   0.    , ...,   2.    ,  38.    ,  71.2833],
       [  0.    ,   0.    ,   1.    , ...,   3.    ,  26.    ,   7.925 ],
       ...,
       [  0.    ,   0.    ,   1.    , ..., 889.    ,  30.    ,  23.45  ],
       [  1.    ,   0.    ,   0.    , ..., 890.    ,  26.    ,  30.    ],
       [  0.    ,   0.    ,   1.    , ..., 891.    ,  32.    ,   7.75  ]])

In [127]:
tt

array([[0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 8.92000e+02,
        3.45000e+01, 7.82920e+00],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 8.93000e+02,
        4.70000e+01, 7.00000e+00],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 8.94000e+02,
        6.20000e+01, 9.68750e+00],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.30700e+03,
        3.85000e+01, 7.25000e+00],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.30800e+03,
        3.00000e+01, 8.05000e+00],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.30900e+03,
        3.00000e+01, 2.23583e+01]])

In [94]:
tc=np.around(tt,2)

In [95]:
tc

array([[0.000e+00, 0.000e+00, 1.000e+00, ..., 8.920e+02, 3.450e+01,
        7.830e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 8.930e+02, 4.700e+01,
        7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 8.940e+02, 6.200e+01,
        9.690e+00],
       ...,
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 1.307e+03, 3.850e+01,
        7.250e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 1.308e+03, 3.000e+01,
        8.050e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 1.309e+03, 3.000e+01,
        2.236e+01]])

In [128]:
xtest.isna().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Fare           0
Embarked       0
dtype: int64

0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: SibSp, dtype: int64

In [129]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(t_x,y,test_size=0.25,random_state=1)

In [130]:
x_test.shape

(223, 18)

In [131]:
tt.shape

(418, 18)

In [132]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(criterion='gini',max_depth = 8,min_samples_split = 10,random_state=5)
clf.fit(x_train,y_train)

RandomForestClassifier(max_depth=8, min_samples_split=10, random_state=5)

In [133]:
y_pred = clf.predict(x_test)

In [134]:
y_pred[:10]

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1])

In [135]:
y_test[:10]

862    1
223    0
84     1
680    0
535    1
623    0
148    0
3      1
34     0
241    1
Name: Survived, dtype: int64

In [136]:
ytest = clf.predict(tt)

In [137]:
xtest['Survived'] = ytest

In [138]:
xtest

PassengerId  Pclass     Sex   Age  SibSp      Fare Embarked  Survived
0            892       3    male  34.5      0    7.8292        Q         0
1            893       3  female  47.0      1    7.0000        S         0
2            894       2    male  62.0      0    9.6875        Q         0
3            895       3    male  27.0      0    8.6625        S         0
4            896       3  female  22.0      1   12.2875        S         0
..           ...     ...     ...   ...    ...       ...      ...       ...
413         1305       3    male  30.0      0    8.0500        S         0
414         1306       1  female  39.0      0  108.9000        C         1
415         1307       3    male  38.5      0    7.2500        S         0
416         1308       3    male  30.0      0    8.0500        S         0
417         1309       3    male  30.0      1   22.3583        C         0

[418 rows x 8 columns]

In [140]:
c = xtest[['PassengerId','Survived']]

In [142]:
c.to_csv('third.csv',index = False)

In [15]:
x

PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
..           ...     ...                                                ...   
886          887       2                              Montvila, Rev. Juozas   
887          888       1                       Graham, Miss. Margaret Edith   
888          889       3           Johnston, Miss. Catherine Helen "Carrie"   
889          890       1                              Behr, Mr. Karl Howell   
890          891       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [25]:
x['Parch'].value_counts()

0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: Parch, dtype: int64

In [8]:
plt.figure(figsize=(10,6))

<Figure size 1000x600 with 0 Axes>

<Figure size 1000x600 with 0 Axes>